name: CI/CD Pipeline

on:
  push:
    branches:
      - '**' # will run on every push to any branch
  pull_request:
    branches:
      - '**' # will run for PRs to any branch

jobs:
  client-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Run client tests
        run: ./gradlew :client:test

  server-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Run server tests
        run: ./gradlew :server:test